import type { RamadanStoreState } from "./evaluate";

export type BadgeTier = "bronze" | "silver" | "gold";
export type BadgeCategory = "journey" | "prayer" | "quran" | "fasting" | "wellness";

export interface BadgeDefinition {
  id: string;
  title: string;
  subtitle: string;
  shareText: string;
  category: BadgeCategory;
  tier: BadgeTier;
  condition: (state: RamadanStoreState) => boolean;
}

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // ── Journey ─────────────────────────────────────────────────────────────
  {
    id: "journey-start",
    title: "Bismillah",
    subtitle: "Started your Ramadan journey",
    shareText: "I started my Ramadan journey with Ramadan Companion!",
    category: "journey",
    tier: "bronze",
    condition: (s) => s.onboarded,
  },
  {
    id: "journey-7days",
    title: "One Week In",
    subtitle: "7 days of tracking",
    shareText: "One week of tracking my Ramadan journey!",
    category: "journey",
    tier: "bronze",
    condition: (s) => s.totalDaysTracked >= 7,
  },
  {
    id: "journey-ai-enabled",
    title: "Coach's Playbook",
    subtitle: "Enabled AI coaching",
    shareText: "Unlocked AI-powered coaching for my Ramadan journey!",
    category: "journey",
    tier: "bronze",
    condition: (s) => s.hasApiKey,
  },
  {
    id: "journey-complete-log",
    title: "Full Picture",
    subtitle: "10 days with complete logs",
    shareText: "10 days of complete daily logs. Tracking every detail!",
    category: "journey",
    tier: "silver",
    condition: (s) => s.daysWithCompleteLog >= 10,
  },
  {
    id: "journal-first",
    title: "First Reflection",
    subtitle: "Wrote your first journal entry",
    shareText: "Started journaling my Ramadan reflections!",
    category: "journey",
    tier: "bronze",
    condition: (s) => s.journalEntries >= 1,
  },
  {
    id: "journal-7",
    title: "Thoughtful Soul",
    subtitle: "7 journal entries",
    shareText: "7 days of Ramadan reflections. Growing through self-awareness!",
    category: "journey",
    tier: "silver",
    condition: (s) => s.journalEntries >= 7,
  },

  // ── Prayer ──────────────────────────────────────────────────────────────
  {
    id: "prayer-streak-3",
    title: "Consistent",
    subtitle: "3-day all-prayers streak",
    shareText: "I prayed all 5 prayers for 3 days straight!",
    category: "prayer",
    tier: "bronze",
    condition: (s) => s.prayerStreak >= 3,
  },
  {
    id: "prayer-streak-7",
    title: "Steadfast",
    subtitle: "7-day all-prayers streak",
    shareText: "One full week of praying all 5 daily prayers!",
    category: "prayer",
    tier: "silver",
    condition: (s) => s.prayerStreak >= 7,
  },
  {
    id: "prayer-streak-21",
    title: "Devoted",
    subtitle: "21-day all-prayers streak",
    shareText: "21 days straight of all 5 daily prayers. Alhamdulillah!",
    category: "prayer",
    tier: "gold",
    condition: (s) => s.prayerStreak >= 21,
  },
  {
    id: "prayer-streak-30",
    title: "Perfect Month",
    subtitle: "30-day all-prayers streak",
    shareText: "A perfect month of prayer. Every prayer, every day. Allahu Akbar!",
    category: "prayer",
    tier: "gold",
    condition: (s) => s.prayerStreak >= 30,
  },
  {
    id: "prayer-fajr-7",
    title: "Dawn Warrior",
    subtitle: "7-day Fajr streak",
    shareText: "7 days waking up for Fajr! The early bird catches the barakah!",
    category: "prayer",
    tier: "silver",
    condition: (s) => s.fajrStreak >= 7,
  },
  {
    id: "prayer-fajr-21",
    title: "Dawn Champion",
    subtitle: "21-day Fajr streak",
    shareText: "21 consecutive days of Fajr. True dedication to the dawn prayer!",
    category: "prayer",
    tier: "gold",
    condition: (s) => s.fajrStreak >= 21,
  },
  {
    id: "prayer-taraweeh-10",
    title: "Night Worshipper",
    subtitle: "10 nights of Taraweeh",
    shareText: "10 nights of Taraweeh prayers this Ramadan!",
    category: "prayer",
    tier: "silver",
    condition: (s) => s.taraweehCount >= 10,
  },
  {
    id: "prayer-taraweeh-27",
    title: "Laylatul Qadr Seeker",
    subtitle: "27 nights of Taraweeh",
    shareText: "27 nights of Taraweeh! Seeking Laylatul Qadr with dedication!",
    category: "prayer",
    tier: "gold",
    condition: (s) => s.taraweehCount >= 27,
  },

  // ── Quran ───────────────────────────────────────────────────────────────
  {
    id: "quran-first-juz",
    title: "First Juz",
    subtitle: "Completed your first Juz",
    shareText: "I completed my first Juz of the Quran this Ramadan!",
    category: "quran",
    tier: "bronze",
    condition: (s) => s.juzCompleted >= 1,
  },
  {
    id: "quran-5-juz",
    title: "Deep Dive",
    subtitle: "5 Juz completed",
    shareText: "5 Juz of the Quran completed this Ramadan!",
    category: "quran",
    tier: "bronze",
    condition: (s) => s.juzCompleted >= 5,
  },
  {
    id: "quran-daily-7",
    title: "Daily Reader",
    subtitle: "7-day Quran reading streak",
    shareText: "7 consecutive days of Quran reading! Building a beautiful habit!",
    category: "quran",
    tier: "bronze",
    condition: (s) => s.quranConsecutiveDays >= 7,
  },
  {
    id: "quran-half",
    title: "Halfway There",
    subtitle: "15 Juz completed",
    shareText: "Halfway through the Quran this Ramadan! 15 Juz done.",
    category: "quran",
    tier: "silver",
    condition: (s) => s.juzCompleted >= 15,
  },
  {
    id: "quran-khatm",
    title: "Khatm al-Quran",
    subtitle: "Completed all 30 Juz",
    shareText: "I completed the entire Quran this Ramadan! Khatm al-Quran!",
    category: "quran",
    tier: "gold",
    condition: (s) => s.juzCompleted >= 30,
  },

  // ── Fasting ─────────────────────────────────────────────────────────────
  {
    id: "first-fast",
    title: "First Fast",
    subtitle: "Completed your first day of fasting",
    shareText: "Completed my first fast this Ramadan!",
    category: "fasting",
    tier: "bronze",
    condition: (s) => s.fastedDays >= 1,
  },
  {
    id: "fasting-sahoor-7",
    title: "Pre-Dawn Fuel",
    subtitle: "7 days with Sahoor",
    shareText: "7 days eating Sahoor! Fueling up before the fast!",
    category: "fasting",
    tier: "bronze",
    condition: (s) => s.daysWithSahoor >= 7,
  },
  {
    id: "fasting-10",
    title: "10 Days Strong",
    subtitle: "10 days of fasting completed",
    shareText: "10 days of fasting this Ramadan! Going strong.",
    category: "fasting",
    tier: "silver",
    condition: (s) => s.fastedDays >= 10,
  },
  {
    id: "fasting-all-meals-7",
    title: "Nutrition Master",
    subtitle: "7 days with all 3 meals logged",
    shareText: "7 days tracking Sahoor, Iftar, and post-Taraweeh meals!",
    category: "fasting",
    tier: "silver",
    condition: (s) => s.daysWithAllMeals >= 7,
  },
  {
    id: "fasting-30",
    title: "Full Ramadan",
    subtitle: "30 days of fasting",
    shareText: "Fasted the entire month of Ramadan! Alhamdulillah!",
    category: "fasting",
    tier: "gold",
    condition: (s) => s.fastedDays >= 30,
  },

  // ── Wellness ────────────────────────────────────────────────────────────
  {
    id: "hydration-streak-3",
    title: "Hydration Habit",
    subtitle: "3-day hydration streak",
    shareText: "3 consecutive days of staying hydrated! Building the habit!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.hydrationStreak >= 3,
  },
  {
    id: "hydration-7",
    title: "Well Hydrated",
    subtitle: "7 days with 8+ glasses of water",
    shareText: "Stayed hydrated during Ramadan — 7 days of 8+ glasses!",
    category: "wellness",
    tier: "silver",
    condition: (s) => s.daysWithFullHydration >= 7,
  },
  {
    id: "hydration-streak-14",
    title: "Hydration Champion",
    subtitle: "14-day hydration streak",
    shareText: "14 consecutive days fully hydrated! Water champion!",
    category: "wellness",
    tier: "gold",
    condition: (s) => s.hydrationStreak >= 14,
  },
  {
    id: "sleep-7",
    title: "Well Rested",
    subtitle: "7 days with 7+ hours of sleep",
    shareText: "7 days of quality sleep this Ramadan! Rest is worship too!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.daysWithAdequateSleep >= 7,
  },
  {
    id: "sleep-consistent",
    title: "Sleep Discipline",
    subtitle: "Consistent sleep schedule",
    shareText: "Maintaining a consistent sleep schedule during Ramadan!",
    category: "wellness",
    tier: "silver",
    condition: (s) => s.sleepConsistencyScore >= 80,
  },
  {
    id: "training-great-5",
    title: "Feeling Great",
    subtitle: "5 great training days",
    shareText: "5 days of feeling great during training while fasting!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.daysWithGreatTraining >= 5,
  },
  {
    id: "training-10",
    title: "Fasting Athlete",
    subtitle: "10 training days while fasting",
    shareText: "10 days training while fasting! True athlete of faith!",
    category: "wellness",
    tier: "silver",
    condition: (s) => s.trainingWhileFasting >= 10,
  },
  {
    id: "dhikr-daily-7",
    title: "Daily Dhikr",
    subtitle: "7 days of tasbeeh",
    shareText: "7 days of daily dhikr! SubhanAllah, Alhamdulillah, Allahu Akbar!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.tasbeehDaysActive >= 7,
  },
  {
    id: "dhikr-1000",
    title: "Remembrance",
    subtitle: "1,000 cumulative tasbeeh",
    shareText: "1,000 tasbeeh counted this Ramadan. SubhanAllah!",
    category: "wellness",
    tier: "silver",
    condition: (s) => s.totalTasbeeh >= 1000,
  },
  {
    id: "dhikr-5000",
    title: "Deep Remembrance",
    subtitle: "5,000 cumulative tasbeeh",
    shareText: "5,000 tasbeeh this Ramadan! Deep in the remembrance of Allah!",
    category: "wellness",
    tier: "gold",
    condition: (s) => s.totalTasbeeh >= 5000,
  },
  {
    id: "series-first",
    title: "First Guide",
    subtitle: "Completed a companion guide episode",
    shareText: "Completed my first AI Companion Guide episode!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.completedEpisodes >= 1,
  },
  {
    id: "series-3-complete",
    title: "Dedicated Learner",
    subtitle: "Completed 3 episodes",
    shareText: "3 lecture episodes completed! Learning and growing!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.completedEpisodes >= 3,
  },
  {
    id: "series-action-items",
    title: "Knowledge to Action",
    subtitle: "5 action items completed",
    shareText: "Turning knowledge into action — 5 action items completed!",
    category: "wellness",
    tier: "silver",
    condition: (s) => s.completedActionItems >= 5,
  },
  {
    id: "series-complete",
    title: "Series Scholar",
    subtitle: "Completed an entire series",
    shareText: "Completed an entire lecture series with the AI Companion!",
    category: "wellness",
    tier: "silver",
    condition: (s) => s.hasCompletedAnySeries,
  },
  {
    id: "good-deeds-10",
    title: "Doer of Good",
    subtitle: "10 days with good deeds",
    shareText: "10 days of recording good deeds! Spreading goodness in Ramadan!",
    category: "wellness",
    tier: "silver",
    condition: (s) => s.daysWithGoodDeeds >= 10,
  },
  {
    id: "partner-connected",
    title: "Accountability",
    subtitle: "Connected with a partner",
    shareText: "Connected with an accountability partner for Ramadan!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.hasPartner,
  },
  {
    id: "schedule-created",
    title: "Game Plan",
    subtitle: "Created a daily schedule",
    shareText: "Created my personalized Ramadan daily schedule!",
    category: "wellness",
    tier: "bronze",
    condition: (s) => s.hasCustomSchedule,
  },
];
